// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFn05tAQpOaFBTBESJzHkBJTZ1eOEVtzI',
    appId: '1:605680871536:web:ee9cdf9479dfda90622cb5',
    messagingSenderId: '605680871536',
    projectId: 'unimart-20261',
    authDomain: 'unimart-20261.firebaseapp.com',
    storageBucket: 'unimart-20261.firebasestorage.app',
    measurementId: 'G-0SXEQ3JZ1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7QIz_pwZYjfWF61Ct0m_btGYfaskbPXs',
    appId: '1:605680871536:android:d2cbbcfb0bb1bd04622cb5',
    messagingSenderId: '605680871536',
    projectId: 'unimart-20261',
    storageBucket: 'unimart-20261.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6p6VPoHtfeXveI4mAV4L6HEVjzg6hck',
    appId: '1:605680871536:ios:b420ce3430a71e31622cb5',
    messagingSenderId: '605680871536',
    projectId: 'unimart-20261',
    storageBucket: 'unimart-20261.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk6p6VPoHtfeXveI4mAV4L6HEVjzg6hck',
    appId: '1:605680871536:ios:b420ce3430a71e31622cb5',
    messagingSenderId: '605680871536',
    projectId: 'unimart-20261',
    storageBucket: 'unimart-20261.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFn05tAQpOaFBTBESJzHkBJTZ1eOEVtzI',
    appId: '1:605680871536:web:a390cef70fbc2340622cb5',
    messagingSenderId: '605680871536',
    projectId: 'unimart-20261',
    authDomain: 'unimart-20261.firebaseapp.com',
    storageBucket: 'unimart-20261.firebasestorage.app',
    measurementId: 'G-BZP2JLL72Y',
  );
}
